// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EC_OK-0]
	_ = x[EC_Unknown - -1]
	_ = x[EC_FormatError - -2]
	_ = x[EC_DataNotExists - -3]
	_ = x[EC_MarshalFail - -4]
	_ = x[EC_UnmarshalFail - -5]
	_ = x[EC_NetworkFail - -6]
	_ = x[EC_ParameterInvalid - -7]
	_ = x[EC_UnknownMessage - -8]
	_ = x[EC_GamesvrError - -9]
	_ = x[EC_TokenInvalid - -10]
	_ = x[EC_AccountReplaced - -11]
	_ = x[EC_ServerBusy - -12]
	_ = x[EC_IMSvrNotFound - -13]
	_ = x[EC_PlayerNoOnline - -14]
}

const _ErrCode_name = "用户已离线聊天服维护中服务器忙，请稍后再试账号被新登录踢出Token无效(验证未通过)游戏服务器链接错误无法识别的消息参数错误网络错误协议解码错误协议编码错误数据不存在数据格式错误未知错误OK"

var _ErrCode_index = [...]uint16{0, 15, 33, 63, 87, 115, 142, 163, 175, 187, 205, 223, 238, 256, 268, 270}

func (i ErrCode) String() string {
	i -= -14
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+-14), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
