// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EC_OK-0]
	_ = x[EC_Unknown - -1]
	_ = x[EC_FormatError - -2]
	_ = x[EC_DataNotExists - -3]
	_ = x[EC_ProtobufMarshalFail - -4]
	_ = x[EC_ProtobufUnmarshalFail - -5]
	_ = x[EC_NetworkFail - -6]
	_ = x[EC_ParameterInvalid - -7]
	_ = x[EC_UnknownMessage - -8]
}

const _ErrCode_name = "无法识别的消息参数错误网络错误Pb解码错误Pb编码错误数据不存在数据格式错误未知错误OK"

var _ErrCode_index = [...]uint8{0, 21, 33, 45, 59, 73, 88, 106, 118, 120}

func (i ErrCode) String() string {
	i -= -8
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+-8), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
