// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssproto.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ping
type MessagePing struct {
	EntityType int32  `protobuf:"varint,1,opt,name=EntityType" json:"EntityType,omitempty"`
	EntityID   uint32 `protobuf:"varint,2,opt,name=EntityID" json:"EntityID,omitempty"`
}

func (m *MessagePing) Reset()                    { *m = MessagePing{} }
func (m *MessagePing) String() string            { return proto.CompactTextString(m) }
func (*MessagePing) ProtoMessage()               {}
func (*MessagePing) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *MessagePing) GetEntityType() int32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *MessagePing) GetEntityID() uint32 {
	if m != nil {
		return m.EntityID
	}
	return 0
}

// router同步server
type MessageSyncServer struct {
	ServerIDs  []int32 `protobuf:"varint,1,rep,packed,name=ServerIDs" json:"ServerIDs,omitempty"`
	ServerType uint32  `protobuf:"varint,2,opt,name=ServerType" json:"ServerType,omitempty"`
}

func (m *MessageSyncServer) Reset()                    { *m = MessageSyncServer{} }
func (m *MessageSyncServer) String() string            { return proto.CompactTextString(m) }
func (*MessageSyncServer) ProtoMessage()               {}
func (*MessageSyncServer) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *MessageSyncServer) GetServerIDs() []int32 {
	if m != nil {
		return m.ServerIDs
	}
	return nil
}

func (m *MessageSyncServer) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func init() {
	proto.RegisterType((*MessagePing)(nil), "pb.MessagePing")
	proto.RegisterType((*MessageSyncServer)(nil), "pb.MessageSyncServer")
}

func init() { proto.RegisterFile("ssproto.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x2e, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0x4c, 0x05, 0x49, 0x4a, 0x9e, 0x5c, 0xdc, 0xbe, 0xa9,
	0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x01, 0x99, 0x79, 0xe9, 0x42, 0x72, 0x5c, 0x5c, 0xae, 0x79, 0x25,
	0x99, 0x25, 0x95, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x48, 0x22,
	0x42, 0x52, 0x5c, 0x1c, 0x10, 0x9e, 0xa7, 0x8b, 0x04, 0x13, 0x50, 0x96, 0x37, 0x08, 0xce, 0x57,
	0x0a, 0xe4, 0x12, 0x84, 0x1a, 0x15, 0x5c, 0x99, 0x97, 0x1c, 0x9c, 0x5a, 0x54, 0x96, 0x5a, 0x24,
	0x24, 0xc3, 0xc5, 0x09, 0x61, 0x79, 0xba, 0x14, 0x03, 0xcd, 0x63, 0x06, 0x9a, 0x87, 0x10, 0x00,
	0x59, 0x07, 0xe1, 0x80, 0xad, 0x83, 0x18, 0x88, 0x24, 0x92, 0xc4, 0x06, 0x76, 0xa8, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xac, 0x1c, 0xcb, 0x06, 0xb9, 0x00, 0x00, 0x00,
}
