// Code generated by go generate. DO NOT EDIT.
package protocol

import "github.com/raochq/gogame/protocol/pb"

const (
	MsgID_MessagePing         = 1 //ping消息
	MsgID_MessageSyncServer   = 2 //服务器间同步
	MsgID_MessageCharLoginReq = 3 //登录
	MsgID_MessageCharLoginRes = 4 //登录结果
	MsgID_MessageErrorNoti    = 5 //错误消息
)

func init() {
	processor = NewProcessor()
	processor.Register(MsgID_MessagePing, (*pb.MessagePing)(nil))
	processor.Register(MsgID_MessageSyncServer, (*pb.MessageSyncServer)(nil))
	processor.Register(MsgID_MessageCharLoginReq, (*pb.MessageCharLoginReq)(nil))
	processor.Register(MsgID_MessageCharLoginRes, (*pb.MessageCharLoginRes)(nil))
	processor.Register(MsgID_MessageErrorNoti, (*pb.MessageErrorNoti)(nil))
}
